//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetail
    {
        public int S_No { get; set; }
        public string Employee_ID { get; set; }
        public string Emp_Name { get; set; }
        public string Designation { get; set; }
        public string Email_Id { get; set; }
        public System.DateTime Date_of_joining { get; set; }
    }
}
