//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int S_No { get; set; }
        public string Device_Id { get; set; }
        public string Emp_Id { get; set; }
        public string Emp_name { get; set; }
        public System.DateTime Date_assign { get; set; }
        public System.DateTime Date_unassign { get; set; }
    }
}
