//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehouse
    {
        public int S_No { get; set; }
        public string Device_ID { get; set; }
        public string Serial_No { get; set; }
        public string Device_Name { get; set; }
        public string Device_Type { get; set; }
        public string Processor { get; set; }
        public string Remarks { get; set; }
        public System.DateTime Purchase_Date { get; set; }
        public string Status { get; set; }
    }
}
